### ISSUE TITLE
When changing pw and inputs a wrong old pw the error 403 is not handled

### ISSUE THREAD

**Issue by mapcentia** [sashuk/dashboard#11]
![image](https://user-images.githubusercontent.com/3850918/58541834-a6b2fb00-81fc-11e9-9d37-a281d772ca06.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/dashboard/commit/4dd08777bdad042a58b2cd7baab702bee429c563

![password](https://user-images.githubusercontent.com/1390758/58549796-ea2e5900-823e-11e9-9019-f4e8a3f9fea7.gif)
