### ISSUE TITLE
Adapt application to work in Apache subfolder

### ISSUE THREAD

**Issue by sashuk** [sashuk/dashboard#14]

**Comment by sashuk** [comment]
@mapcentia The app code now is aware if it is served from the subdirectory, also the `.htaccess` in `geocloud/public` should be modified to serve requests to the application located in `geocloud/public/dashboard` (instructions are listed in https://github.com/sashuk/dashboard#installation).

The development mode is not affected and is launched using the regular `npm start`.

**Comment by mapcentia** [comment]
@sashuk 
With these Apache2 rules, I guess there must be an `index.html` file in `/dashboard/`. But there is not?
```
# Rewrite rules for React app, located in dashboard subdirectory - return
# the index.html unless the requested file / directory exists
RewriteRule ^dashboard/index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^dashboard/(.*) dashboard/index.html [L]
```

**Comment by sashuk** [comment]
@mapcentia Yes, the `dashboard` is supposed to be built and copied in the folder. Should it be done upon Docker image installation? Or it should be included as part of the GC2 repository?

**Comment by mapcentia** [comment]
@sashuk Its should be done in the Docker image build of GC2: https://github.com/mapcentia/dockerfiles/blob/master/gc2core/stable/Dockerfile

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by mapcentia** [comment]
@sashuk Is it about running `npm run build` and copy `build` folder files to `dashboard`. Seems to work

**Comment by sashuk** [comment]
@mapcentia The Dashboard deployment script was added in https://github.com/sashuk/dockerfiles/commit/863ce0dc3f3f79d74184c8d55c6e260169d2b0b7#diff-4052b959d749862b36b050c52719297eR56.

However, it works only with the latest `geocloud2` changes, as `geocloud2 sashuk:master` is 33 commits ahead of `geocloud2  mapcentia:master` (these 33 commits are basically changes in API and `.htaccess` file for handling React app) - so, either the `mapcentia`'s `dashboard` and `geocloud2` repositories should be synced or all occurrences of `/mapcentia/` can be replaced with `/sashuk/` (this method could be used just to test things).

**Comment by mapcentia** [comment]
@sashuk I've pull your geocloud2 master branch into a `develop` branch in my repo and it works alright. But the `sw.js` script is not loaded:
![image](https://user-images.githubusercontent.com/3850918/58861065-ddca5600-86ad-11e9-9471-6ed3c8ac7158.png)
I guess the folder `/dashboard/` is missing from the URL

**Comment by sashuk** [comment]
@mapcentia The `offline-plugin` now uses the environment constant which specifies the deployment subdirectory, implemented in https://github.com/sashuk/dashboard/commit/f3a156bcc85ff8f9f7a1cff9b3bc09b9bf940f95

**Comment by mapcentia** [comment]
@sashuk I can't this to work. `sw.js` is still fetched from root folder `/`. Even if I omit the check `if (process.env.NODE_ENV === 'production')`

**Comment by sashuk** [comment]
@mapcentia Is the `.env` exact as the https://github.com/sashuk/dashboard/blob/master/.env.production?

**Comment by mapcentia** [comment]
@sashuk Yes

**Comment by sashuk** [comment]
@mapcentia Could you please specify if the offline capability required for the Dashboard at this point?

**Comment by mapcentia** [comment]
@sashuk It is not

**Comment by sashuk** [comment]
@mapcentia Could you please try now (last changes at https://github.com/sashuk/dashboard/commit/753dabafdb23556c2af674ca3d94e5e027f3c464)?

**Comment by mapcentia** [comment]
@sashuk Works without errors. Closing
