### ISSUE TITLE
Bug while using the config editor

### ISSUE THREAD

**Issue by mapcentia** [sashuk/dashboard#15]
When typing in the config editor, the screen goes blank:
![image](https://user-images.githubusercontent.com/3850918/58864711-87f9ac00-86b5-11e9-90af-8c59fac25772.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/dashboard/commit/d98974ad2b1e49f3d47d2111ac5e504ce6685e6b

![editor](https://user-images.githubusercontent.com/1390758/58879165-94a6f000-8707-11e9-8269-c80382b5f858.gif)
