### ISSUE TITLE
If the user is registered in different databases with different names, but same email, give him a database choice on sign-in

### ISSUE THREAD

**Issue by sashuk** [sashuk/dashboard#16]

**Comment by sashuk** [comment]
@mapcentia Could you please specify if the user should be able to enter either name or email during the first step of `/sign-in` in Dashboard? So, if he enters the email, the backend looks for all databases where this email is registered and the user has a choice to sign in in any of the databases.

**Comment by mapcentia** [comment]
@sashuk That's would be a nice feature to have. Thanks

**Comment by sashuk** [comment]
@mapcentia The feature was implemented in https://github.com/sashuk/dashboard/commit/c1da6bfd8cdab215ff3fb2884c2c3be85bf45f18 and https://github.com/sashuk/geocloud2/commit/5dc8f7ff852245068c0eba5d1dcba3ba1137d4d7

For such configuration:
```
sashuk (super-user)
|--- sashuksub testtest@example.com (sub-user)
sashuk_duo
|--- sashuksub test@test.ru
sashuk_tre
|--- sashuknotsub testtest@example.com
```

when `testtest@example.com` is entered on the first step on authentication, `sashuk` and `sashuk_tre` databases are offered before entering the password.

![dashboard](https://user-images.githubusercontent.com/1390758/59207256-4dbe6c00-8bd9-11e9-9114-994bbbb52483.png)
