### ISSUE TITLE
PHP session cookie is not deleted when sigin out

### ISSUE THREAD

**Issue by mapcentia** [sashuk/dashboard#17]
![Peek 2019-06-06 08-31](https://user-images.githubusercontent.com/3850918/59011629-9bcc1c00-8835-11e9-9aa6-4a655a934511.gif)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/dashboard/commit/91744135a472f3c98ccd8d3bf8dbd33d30fc43bf
