### ISSUE TITLE
Set language after window.gc2Al

### ISSUE THREAD

**Issue by mapcentia** [sashuk/dashboard#18]
I've changed Dashboard, so settings from GC2 are available:
https://github.com/mapcentia/dashboard/commit/5409b5c1cb74ab02e076357975c76449de647201

Is it possible to set language after `window.gc2Al`?

**Comment by sashuk** [comment]
@mapcentia Sure, I will make Dashboard pick up the language setting on startup (assuming that the idea is to make the Dashboard have the same language as the GC2).

**Comment by sashuk** [comment]
@sashuk Keep in mind https://github.com/mapcentia/geocloud2/commit/469052c8a86e0d6e3f733a6aed4151881e1e1144

**Comment by sashuk** [comment]
@mapcentia Could you please specify if `vidUrl` should be fetched from GC2 as well (https://github.com/mapcentia/geocloud2/commit/469052c8a86e0d6e3f733a6aed4151881e1e1144)?

**Comment by mapcentia** [comment]
@sashuk I've already done this in mapcentia/dashboard

**Comment by sashuk** [comment]
@mapcentia What if configurations will reside in Redux store? In the very startup of the application, the `/api/v1/baselayerjs` could be pulled by Dashboard itself (not as an HTML `<script/>` tag), showing the loading spinner along (just like in Vidi).

There could be a situation when the `/api/v1/baselayerjs` request is taking too long, so when `vidUrl` is needed in the React app it is still empty (and when the global variable will be set, the update will still not be triggered).

**Comment by mapcentia** [comment]
@sashuk In this case we need a API which return the App.php values as JSON. But that is a small thing to do. Go ahead.

**Comment by sashuk** [comment]
@mapcentia Got it!

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/dashboard/commit/398d563b76e7820aed17dd9626d34ee8989a5a5b along with the GC2 modifications at https://github.com/sashuk/geocloud2/commit/d3d34c626ad3ab8e35c46a3414ad4c78c7680403
