### ISSUE TITLE
Enable Enter key stroke on user name input

### ISSUE THREAD

**Issue by mapcentia** [sashuk/dashboard#19]
Its not possible to use Enter key. It's seems that the form GET submits to the same page.
![image](https://user-images.githubusercontent.com/3850918/59409942-c7ac4c00-8db7-11e9-9d67-c01a08420035.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/dashboard/commit/c021ccdcac7664920475026d1b7bcec251168ce9
