### ISSUE TITLE
When creating a sub-user, the property usergroup is set to string "null"

### ISSUE THREAD

**Issue by mapcentia** [sashuk/dashboard#20]
When not selecting a user group, the string `null` is send. This should be the NULL value:

![image](https://user-images.githubusercontent.com/3850918/59422188-43b28e00-8dd0-11e9-8b87-ceb2d7cf8c92.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/dashboard/commit/4a8c090d6d4477f5e6370e8128e031015a309d93

![data](https://user-images.githubusercontent.com/1390758/59423083-07992080-8e04-11e9-9308-3aa136196841.PNG)

**Comment by mapcentia** [comment]
@sashuk It is still a string? What I mean, is the NULL value 

```json
{
"subuser": null, // Right
"subuser": "null", // Wrong
}
```

**Comment by sashuk** [comment]
@mapcentia I was wrong, as the point was to process `usergroup` parameter here - https://github.com/sashuk/geocloud2/blob/master/app/models/User.php#L134

Now if the `usergroup` is empty, it is detected as empty one on the PHP side as well.

`usergroup` is empty:
![no_group](https://user-images.githubusercontent.com/1390758/59424430-8f802a00-8e06-11e9-8c32-f8238f3edbf0.PNG)

`usergroup` is not empty:
![group](https://user-images.githubusercontent.com/1390758/59424444-96a73800-8e06-11e9-859a-502a0fd3fc36.PNG)
