### ISSUE TITLE
Switch of validity check while typing in JSON editor

### ISSUE THREAD

**Issue by mapcentia** [sashuk/dashboard#22]
While you type in JSON editor the validity is checked, which makes the cursor switch location. Could the check be performed only when you save the edit?
![image](https://user-images.githubusercontent.com/3850918/59844760-eed8bf80-935b-11e9-9e39-8a65bc7ab30d.png)

**Comment by sashuk** [comment]
@mapcentia The configuration editing was modified in https://github.com/sashuk/dashboard/commit/d4069a257c038be73a13a8d0eb02721767967c93

Demo:

![json](https://user-images.githubusercontent.com/1390758/59870185-a3f49180-93c7-11e9-8ce8-3f557f5a44cb.gif)
