### ISSUE TITLE
JSON editor is escaping qoutes and adding newline chars

### ISSUE THREAD

**Issue by mapcentia** [sashuk/dashboard#23]
Request on API:
`curl http://127.0.0.1/api/v2/configuration/mydb/configuration_test_5d0c9757b2268111962423.json`

Result:

`"{\n    \"snapshot\": \"state_snapshot_0ab65ad0-93fe-11e9-b600-496a7d3e9dc1\",\n    \"brandName\": \"MapCentia ApS\",\n    \"aboutBox\": \"<p>My awesome web map</p>\",\n    \"enabledExtensions\": [\n        \"conflictSearch\",\n        \"streetView\",\n        \"coordinates\",\n        \"session\",\n        \"editor\",\n        \"offlineMap\"\n    ],\n    \"template\": \"default.tmpl\"\n}`

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/dashboard/commit/879bb5a2ae0d71be77f3ad3940a69eef9ccf2dcc
