### ISSUE TITLE
Vidi link is not set correctly

### ISSUE THREAD

**Issue by sashuk** [sashuk/dashboard#26]

**Comment by mapcentia** [comment]
@sashuk It seems to work alright on severel installations?

**Comment by sashuk** [comment]
@mapcentia This is more about configuring the AKS GC2 pod, the external URL of the Vidi should be provided to the GC2 pod

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/gc2_aks/commit/26e577d06f41d0f1dc7c3abfae49fbc05ac2784a
