### ISSUE TITLE
Vidi configuration storage

### ISSUE THREAD

**Issue by sashuk** [sashuk/dashboard#6]

**Comment by sashuk** [comment]
The wireframe for Vidi configuration storage was drawn:

![configuration_sharing](https://user-images.githubusercontent.com/1390758/56434640-ff42ce80-6307-11e9-9526-3f6449ee9f0a.jpg)

**Comment by sashuk** [comment]
@mapcentia Could you please check if the interface has all features that are needed for the configurations management?

**Comment by mapcentia** [comment]
@sashuk Looks good. Go for it. There must be a link to Vidi with the config. Like `https://...../app/vac2/?conf=blackbassin.json`

**Comment by sashuk** [comment]
@mapcentia Could you please specify what URL should the Vidi link have, as there are `N` schemas and `M` configurations (demo is presented below). Should there be some kind of selector for every configuration, where the user selects the schema from the dropdown list and then the Vidi URL is generated for it?

Vidi URL is kept in a separate configuration setting (https://github.com/sashuk/dashboard/commit/62ca78ededf7c542a3ef3e6d0607d8c6d2752e7e)

![schemas](https://user-images.githubusercontent.com/1390758/57094336-e93f0000-6d42-11e9-872e-e88447809f38.gif)

**Comment by mapcentia** [comment]
@sashuk 
As I see it, there're two typical ways to start Vidi: 1) with a schema like `/app/database/schema` and with a config like `/app/database/?config=test.json`

So from the CONFIGURATIONS tab, where should be a button like the one in SCHEMAS. The Vidi host URL should be a configuration in the dashboard.

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia Configurations and schemas are using the `vidiURL` config setting, implemented in https://github.com/sashuk/dashboard/commit/a03a51aa5dced18ff625b3a7d418927db4313691
