### ISSUE TITLE
Its not possible to login with sub-user when there're two with same name

### ISSUE THREAD

**Issue by mapcentia** [sashuk/dashboard#9]
When two or more sub-users share the same name, the login dialog should present a choise between databases. So maybe some kind of two/three step login is need:

`Type user name -> Select database -> Type pw`

`Select database` should not show if super-user or sub-user name is not used more than one. 

![image](https://user-images.githubusercontent.com/3850918/58491499-5fcaf400-816f-11e9-89eb-dfd6a0282734.png)

**Comment by sashuk** [comment]
@mapcentia Could you please specify if it is acceptable to have a user with the same name **and** email that has multiple databases  (is it possible that one person is registered in different databases with the same name and email)?

Right now two different superusers can create sub-users with the same name, but *different* email address (assuming that different emails belong to physically different people), so it is not possible to create users with same name **and** email.

Corresponding test cases:

```
✔ UserManagementCest: Should create subuser for different superuser with existing name (0.54s)
✔ UserManagementCest: Should not allow sub user with conflicting name authorize with name only (0.01s)
✔ UserManagementCest: Should allow sub user with conflicting name authorize with name and email (0.08s)
```

**Comment by mapcentia** [comment]
@sashuk A person needs to be registered in two or more databases. So we need to drop the unique constrain on email

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia Could you please consider the following example - the person has an email `test@test.com` and is registered in two databases - `A database` (having name `test` and password `123`) and in `B database` (having name `test` and password `456`). When he types in his user name `test`, the next step proposes him to choose from `A database` and `B database` and then enter the password. Should the user be authorized, if he selects the `A database` and enters the password from the different database (`456` for `B database`)? There are two options:
1. Authorize a user (so, a single user can actually have multiple passwords);
2. Do not authorize the user and ask him to enter the password for the selected database (basically, it means that user should remember passwords for every database and the database selection is available only if the user has the same password for more than one databases, so the order of steps should be changed).

Could you please specify what option should be implemented? I think that the first one is a lot more comfortable for users.

**Comment by mapcentia** [comment]
@sashuk I think that no. 1 introduce a security risk. If the database owner (the super user) is creating sub users with same name in two databases and using the same dummy email, the sub users can gain access to both databases

**Comment by sashuk** [comment]
@mapcentia Agree, there is such a possibility (as well as the possibility of having users with the same name **and** email **and** password for different databases). But maybe to enforce the responsible email assignment? So `the same email = the same person`, otherwise email becomes just another `name` field with special formatting as it does not correlate with the real world. Also, it will become a problem if emailing will be implemented (restoring passwords, notifications etc.), as the same email will correspond to more than one physical persons.

Ideally, I think, it will be better to separate the `user` and `database` entity (to implement Many-To-Many relation), so when super-user wants to create a sub-user with the existing email he sees that such user already is registered so super-user is able to give access to an already existing user (for example, like in Github when sharing repository access), but there will be a lot to change.

**Comment by mapcentia** [comment]
@sashuk Your idea about separating user from database is good - and this should have been done back when we started the GC2 project. But it'll take a lot of changes and we need to get this working. 

So for now the concept is: `User1@DatabaseA` is another user than `User1@DatabaseB`. Even if the emails are the same. `User1` could be a single real person, which in this case has two accounts.

The idea about responsible email assignment is something I have thought about (if you mean sending a email with a activate link?). As you write, this could indicate that `User1@DatabaseA` and `User1@DatabaseB` is the same real person. Lets do this in its own issue.

So its option no. 2

**Comment by sashuk** [comment]
@mapcentia Alright got it! So, now the authorization workflow should look like this for sub-users then:
1. Type in the name;
2. Backend returns available databases for this name;
3. Sub-user selects the database and enters the password for it;

Could you please check if this is correct?

There could be another way to discover available databases when user names are different in databases but the **email is the same** - https://github.com/sashuk/dashboard/issues/16

**Comment by mapcentia** [comment]
@sashuk Its correct. Important: If sub-user name only exists for one database, when just start session. This way the `api/v2/session` API will act unchanged if only one sub-user is using the name.

**Comment by sashuk** [comment]
@mapcentia Thanks for the clarification! Everything is clear now

**Comment by sashuk** [comment]
@mapcentia The feature was implemented in https://github.com/sashuk/dashboard/commit/a4d377379836a5baef1442fba4a8ad083a046421 and https://github.com/sashuk/geocloud2/commit/e1222a252bc2b058fc782c3f0a915e07cf560879

The same email for users with the same name in different databases will be implemented as part of the https://github.com/sashuk/dashboard/issues/16

![auth](https://user-images.githubusercontent.com/1390758/59018933-9ee8fb80-8879-11e9-94ff-2325b7ad0fcf.gif)
